export const REQUESTED_DOG = 'REQUESTED_DOG';
export const REQUESTED_DOG_SUCCEEDED = 'REQUESTED_DOG_SUCCEEDED';
export const REQUESTED_DOG_FAILED = 'REQUESTED_DOG_FAILED';

export const FETCHED_DOG = 'FETCHED_DOG';

